services:
  adventurer:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${ADVENTURER_DISCORD_TOKEN}
      DISCORD_PUBLIC_KEY: ${ADVENTURER_DISCORD_PUBLIC_KEY}
      DISCORD_APPLICATION_ID: ${ADVENTURER_DISCORD_APPLICATION_ID}
      DISCORD_MENTION_ROLE_IDS: ${ADVENTURER_DISCORD_MENTION_ROLE_IDS:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MODEL: ${ADVENTURER_OPENAI_MODEL:-gpt-4o}
      KARAKURI_API_BASE_URL: ${KARAKURI_API_BASE_URL:-http://host.docker.internal:3000/api}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      KARAKURI_API_KEY: ${ADVENTURER_KARAKURI_API_KEY}
      AGENT_DIR: /app/agent
      BOT_NAME: ${ADVENTURER_BOT_NAME:-adventurer}
      DATA_DIR: /app/data
      PORT: ${ADVENTURER_PORT:-3101}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${ADVENTURER_PORT:-3101}:${ADVENTURER_PORT:-3101}
    volumes:
      - ${ADVENTURER_AGENT_DIR:-./agents/adventurer}:/app/agent:ro
      - ${ADVENTURER_DATA_DIR:-./data/adventurer}:/app/data

  scholar:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${SCHOLAR_DISCORD_TOKEN}
      DISCORD_PUBLIC_KEY: ${SCHOLAR_DISCORD_PUBLIC_KEY}
      DISCORD_APPLICATION_ID: ${SCHOLAR_DISCORD_APPLICATION_ID}
      DISCORD_MENTION_ROLE_IDS: ${SCHOLAR_DISCORD_MENTION_ROLE_IDS:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MODEL: ${SCHOLAR_OPENAI_MODEL:-gpt-4o-mini}
      KARAKURI_API_BASE_URL: ${KARAKURI_API_BASE_URL:-http://host.docker.internal:3000/api}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      KARAKURI_API_KEY: ${SCHOLAR_KARAKURI_API_KEY}
      AGENT_DIR: /app/agent
      BOT_NAME: ${SCHOLAR_BOT_NAME:-scholar}
      DATA_DIR: /app/data
      PORT: ${SCHOLAR_PORT:-3102}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${SCHOLAR_PORT:-3102}:${SCHOLAR_PORT:-3102}
    volumes:
      - ${SCHOLAR_AGENT_DIR:-./agents/scholar}:/app/agent:ro
      - ${SCHOLAR_DATA_DIR:-./data/scholar}:/app/data
