#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

DEBUG_STATE=".debug-state"
DEBUG_WRANGLER="wrangler.debug.toml"
WORKER_NAME="karakuri-world-ui-debug"
R2_NAME="karakuri-world-ui-debug-snapshot"

# ==== Step 1: Create Cloudflare resources (first time only) ====
if [ ! -f "$DEBUG_STATE" ]; then
  echo "===== デバッグ環境の初期セットアップ (Step 1/2) ====="
  echo ""

  read -rp "本体サーバーの URL (例: https://kw.example.com): " KW_BASE_URL
  if [ -z "$KW_BASE_URL" ]; then
    echo "Error: KW_BASE_URL は必須です"
    exit 1
  fi

  echo ""
  echo "R2 バケットを作成中..."
  R2_OUTPUT=$(npx -y wrangler r2 bucket create "$R2_NAME" 2>&1) || true
  echo "$R2_OUTPUT"

  if ! npx -y wrangler r2 bucket list 2>/dev/null | grep -q "$R2_NAME"; then
    echo "Error: R2 バケット '$R2_NAME' の作成・検出に失敗しました"
    exit 1
  fi
  echo "R2 バケット '$R2_NAME' を確認しました"

  echo ""
  echo "R2 バケットに CORS ルールを適用中 (debug: AllowedOrigins=*)..."
  npx -y wrangler r2 bucket cors set "$R2_NAME" --file scripts/r2-cors-debug.json --force

  cat > "$DEBUG_STATE" <<STATE
KW_BASE_URL=$KW_BASE_URL
R2_NAME=$R2_NAME
WORKER_NAME=$WORKER_NAME
SETUP_PHASE=resources_created
STATE

  echo ""
  echo "===== Cloudflare リソースの作成が完了しました ====="
  echo ""
  echo "次に Cloudflare ダッシュボードで以下を設定してください:"
  echo "  1. R2 バケット '$R2_NAME' にカスタムドメインを接続"
  echo "  2. スナップショットパスに Cache Rules を設定:"
  echo "     - Cache Everything on snapshot/manifest.json"
  echo "     - Edge TTL: 5 seconds"
  echo ""
  echo "設定が完了したら、再度 npm run debug:start を実行してください。"
  exit 0
fi

# shellcheck disable=SC1090
source "$DEBUG_STATE"

# ==== Step 2: Configure snapshot URL (after R2 custom domain setup) ====
if [ "${SETUP_PHASE:-}" = "resources_created" ]; then
  echo "===== デバッグ環境の初期セットアップ (Step 2/2) ====="
  echo ""

  read -rp "R2 スナップショット manifest の公開 URL (例: https://snapshot.example.com/snapshot/manifest.json): " SNAPSHOT_URL
  if [ -z "$SNAPSHOT_URL" ]; then
    echo "Error: SNAPSHOT_URL は必須です"
    exit 1
  fi

  grep -v '^SETUP_PHASE=' "$DEBUG_STATE" > "$DEBUG_STATE.next" && mv "$DEBUG_STATE.next" "$DEBUG_STATE"
  echo "SNAPSHOT_URL=$SNAPSHOT_URL" >> "$DEBUG_STATE"
  echo "SETUP_PHASE=configured" >> "$DEBUG_STATE"

  # shellcheck disable=SC1090
  source "$DEBUG_STATE"
fi

if [ -z "${SNAPSHOT_URL:-}" ]; then
  echo "Error: SNAPSHOT_URL が未設定です。.debug-state を削除して debug:start をやり直してください。"
  exit 1
fi

VITE_DEV_PORTS="${DEBUG_VITE_PORTS:-5173 5174}"
LAN_IPS=$(node -e "const os=require('os');const a=Object.values(os.networkInterfaces()).flat().filter(n=>n&&n.family==='IPv4'&&!n.internal).map(n=>n.address);process.stdout.write(a.join(' '))" 2>/dev/null || true)

CORS_ORIGINS=""
append_origin() {
  if [ -z "$1" ]; then return; fi
  if [ -n "$CORS_ORIGINS" ]; then CORS_ORIGINS="$CORS_ORIGINS,"; fi
  CORS_ORIGINS="${CORS_ORIGINS}$1"
}
for port in $VITE_DEV_PORTS; do
  append_origin "http://localhost:$port"
  append_origin "http://127.0.0.1:$port"
  for ip in $LAN_IPS; do
    append_origin "http://$ip:$port"
  done
done
if [ -n "${DEBUG_CORS_EXTRA_ORIGINS:-}" ]; then
  append_origin "$DEBUG_CORS_EXTRA_ORIGINS"
fi

cat > "$DEBUG_WRANGLER" <<EOF2
name = "$WORKER_NAME"
main = "worker/src/index.ts"
compatibility_date = "2025-04-14"

[vars]
KW_BASE_URL = "$KW_BASE_URL"
AUTH_MODE = "public"
HISTORY_CORS_ALLOWED_ORIGINS = "$CORS_ORIGINS"

[[durable_objects.bindings]]
name = "UI_BRIDGE"
class_name = "UIBridgeDurableObject"

[[migrations]]
tag = "plan04-ui-bridge"
new_sqlite_classes = ["UIBridgeDurableObject"]

[[r2_buckets]]
binding = "SNAPSHOT_BUCKET"
bucket_name = "$R2_NAME"
EOF2

if ! grep -q "^SECRETS_SET=true$" "$DEBUG_STATE" 2>/dev/null; then
  echo ""
  echo "KW_ADMIN_KEY シークレットを設定してください:"
  npx -y wrangler secret put KW_ADMIN_KEY -c "$DEBUG_WRANGLER"
  echo ""
  echo "SNAPSHOT_PUBLISH_AUTH_KEY シークレットを設定してください:"
  echo "  ※ 本体サーバー側の SNAPSHOT_PUBLISH_AUTH_KEY と同じ値を入力してください"
  npx -y wrangler secret put SNAPSHOT_PUBLISH_AUTH_KEY -c "$DEBUG_WRANGLER"
  echo "SECRETS_SET=true" >> "$DEBUG_STATE"
fi

echo ""
echo "Worker をデプロイ中..."
DEPLOY_OUTPUT=$(npx -y wrangler deploy -c "$DEBUG_WRANGLER" 2>&1)
echo "$DEPLOY_OUTPUT"

WORKER_URL=$(echo "$DEPLOY_OUTPUT" | grep -oE 'https://[^[:space:]]+\.workers\.dev' | head -1 || true)
if [ -n "$WORKER_URL" ]; then
  if [ -f "$DEBUG_STATE" ]; then
    grep -v '^WORKER_URL=' "$DEBUG_STATE" > "$DEBUG_STATE.next" && mv "$DEBUG_STATE.next" "$DEBUG_STATE"
  fi
  echo "WORKER_URL=$WORKER_URL" >> "$DEBUG_STATE"
fi

# shellcheck disable=SC1090
source "$DEBUG_STATE"

if [ -z "${WORKER_URL:-}" ]; then
  echo ""
  echo "Warning: Worker URL を検出できませんでした"
  echo ".debug-state に WORKER_URL=https://... を手動で追記してから再実行してください"
  exit 1
fi

cat > .env.local <<EOF2
# Generated by debug:start — do not edit manually
VITE_SNAPSHOT_URL=$SNAPSHOT_URL
VITE_AUTH_MODE=public
VITE_API_BASE_URL=${WORKER_URL}/api/history
VITE_PHASE3_EFFECTS_ENABLED=false
EOF2

echo ""
echo ".env.local を更新しました"
echo "  VITE_SNAPSHOT_URL=$SNAPSHOT_URL"
echo "  VITE_API_BASE_URL=${WORKER_URL}/api/history"
